name: adventurous_learner_app
description: The Adventurous Learner App

publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.2

  # State and route management
  get: 4.6.5

  # Otp fields
  pin_code_fields: 7.4.0

  # Shimmer effect
  shimmer: 2.0.0

  # Launching urls
  url_launcher: 6.1.2

  # Networking and api calls
  http: 0.13.4

  # User latitude and longitude
  location: 4.4.0

  # Local storage
  shared_preferences: 2.0.15

  # Image picker
  image_picker: 0.8.5+3

  # Cache image
  cached_network_image: 3.2.1

  # Fonts
  google_fonts: 3.0.1

  # Rating bar
  flutter_rating_bar: 4.0.1

  # form data requests
  dio: ^4.0.6

  # google maps
  google_maps_flutter: ^2.1.9

  # read more
  readmore: ^2.1.0

  # notifications
  onesignal_flutter: ^3.4.1

  # firebase
  firebase_core: ^1.22.0

  # date formatting
  intl: ^0.17.0

  # timeago
  timeago: ^3.3.0

  # open pdf
  flutter_cached_pdfview: ^0.4.1

  # typeahead
  flutter_typeahead: ^4.1.1

  # share app
  share_plus: ^4.2.0

  # html reader
  flutter_html: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"



flutter_icons:
  image_path_android: "assets/logo/app_icon.png"
  image_path_ios: "assets/logo/app_icon_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: "assets/logo/splash.png"
  color: "#ffffff"

  android_12:
    background_image: "assets/logo/splash.png"
    color: "#ffffff"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/doc/


