name: adventurous_learner_app
description: The Adventurous Learner App

publish_to: 'none'

version: 3.0.0+01

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.2

  # State and route management
  get: ^4.6.6

  # Otp fields
  pin_code_fields: ^8.0.1

  # Shimmer effect
  shimmer: ^3.0.0

  # Launching urls
  url_launcher: ^6.3.0

  # Networking and api calls
  http: ^1.2.2

  # User latitude and longitude
  location: ^6.0.2

  # Local storage
  shared_preferences: ^2.3.2

  # Image picker
  image_picker: ^1.1.2

  # Cache image
  cached_network_image: ^3.4.1

  # Fonts
  google_fonts: ^6.2.1

  # Rating bar
  flutter_rating_bar: 4.0.1

  # form data requests
  dio: ^5.7.0

  # google maps
  google_maps_flutter: ^2.1.9

  # read more
  readmore: ^3.0.0

  # notifications
  onesignal_flutter: ^3.5.3

  # firebase
  firebase_core: ^3.4.1

  # date formatting
  intl: ^0.19.0

  # timeago
  timeago: ^3.3.0

  # open pdf
  flutter_cached_pdfview: ^0.4.1

  # typeahead
  flutter_typeahead: ^4.8.0

  # share app
  share_plus: ^10.0.2

  # html reader
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  image_path_android: "assets/logo/ios_logo.png"
  image_path_ios: "assets/logo/ios_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: "assets/logo/ios_logo.png"
  color: "#ffffff"

  android_12:
    background_image: "assets/logo/ios_logo.png"
    color: "#ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/doc/


