name: adventurous_learner_app
description: The Adventurous Learner App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.2

  # State and route management
  get: 4.6.5

  # Otp fields
  pin_code_fields: 7.4.0

  # Shimmer effect
  shimmer: 2.0.0

  # Launching urls
  url_launcher: 6.1.2

  # Networking and api calls
  http: 0.13.4

  # User latitude and longitude
  location: 4.4.0

  # Local storage
  shared_preferences: 2.0.15

  # Image picker
  image_picker: 0.8.5+3

  # Cache image
  cached_network_image: 3.2.1

  # Fonts
  google_fonts: 3.0.1

  flutter_native_splash:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/logo/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: "assets/logo/splash.png"
  color: "#ffffff"

  android_12:
    background_image: "assets/logo/splash.png"
    color: "#ffffff"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    #     - assets/gif/

